### PR TITLE
[UPDATE] Adds 1.28 -> 1.31 of CPI, Adds 3.1.2 -> 3.3.1 of the CSI

### PR DESCRIPTION
**Pull request by addyess**
### Overview
* Update vsphere cloud provider images
* Update the `update.py` 
    * to filter images which can longer be sync'd b/c upstream dropped those images
    * filter out releases which we didn't sync in time (1.27)

[LP#2083999](https://bugs.launchpad.net/charm-vsphere-cloud-provider/+bug/2083999)

Huge thanks to @jblesener for bringing this to my attention
This can replace #32

### CODE REVIEW

**Comment by addyess** [comment]
@jblesener it's on slate to get into the charm soon

**Review by mateoflorido — APPROVED** [review]
LGTM!

**Comment by addyess** [comment]
@jblesener would you be willing to check 1.31/edge charm to see if it fits your liking?

**Comment by jblesener** [comment]
@addyess yep, working fine here. thanks for pushing this through!

**Pull request merged**
