### PR TITLE
Update manifests for CSI to 3.3.1 and CPI to 1.31

### PR DESCRIPTION
**Pull request by jblesener**
Looks like the manifests haven't been updated in some time and the charm doesn't have the versions for the currently supported versions of Charmed Kubernetes (1.31, 1.30, 1.29). Additionally, VMware recommends CSI version 3.3.0+ for use with vSphere 8.0 Update 3.

CPI compat: https://github.com/kubernetes/cloud-provider-vsphere/blob/master/README.md#compatibility-with-kubernetes
CSI compat: https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html

### CODE REVIEW

**Comment by addyess** [comment]
@jblesener thanks so much for this PR

could you also update `.github/workflows/ci.yaml`

```diff
-    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
+    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
```

**Comment by jblesener** [comment]
@addyess sure, all set!

**Comment by addyess** [comment]
@jblesener i don't ACTUALLY have access to a vsphere environment to test this.  Do you?

**Comment by jblesener** [comment]
@addyess I do have some vsphere environments I can test on. I had some trouble building the charm using charmcraft earlier but was able to figure it out. Applying the updated charm results in stuck Deployment/DaemonSet since it can't pull images from rocks.canonical.com (ex: rocks.canonical.com:443/cdk/sig-storage/csi-attacher:v4.5.1). Is there a process to get those images mirrored? These are the images the updated manifests use (some might also be used in the older manifests):

gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.2.1
gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.27.0
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.0.2
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.0.3
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.1.0
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.1.1
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.1.2
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.2.0
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.3.0
gcr.io/cloud-provider-vsphere/csi/release/driver:v3.3.1
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.0.2
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.0.3
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.1.0
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.1.1
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.1.2
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.2.0
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.3.0
gcr.io/cloud-provider-vsphere/csi/release/syncer:v3.3.1
k8s.gcr.io/sig-storage/csi-attacher:v4.2.0
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.7.0
k8s.gcr.io/sig-storage/csi-provisioner:v3.4.0
k8s.gcr.io/sig-storage/csi-resizer:v1.7.0
k8s.gcr.io/sig-storage/csi-snapshotter:v6.2.1
k8s.gcr.io/sig-storage/livenessprobe:v2.9.0
registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.28.0
registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.29.0
registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.30.1
registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.31.0
registry.k8s.io/sig-storage/csi-attacher:v4.3.0
registry.k8s.io/sig-storage/csi-attacher:v4.5.0
registry.k8s.io/sig-storage/csi-attacher:v4.5.1
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
registry.k8s.io/sig-storage/csi-provisioner:v4.0.1
registry.k8s.io/sig-storage/csi-resizer:v1.10.0
registry.k8s.io/sig-storage/csi-resizer:v1.10.1
registry.k8s.io/sig-storage/csi-resizer:v1.8.0
registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
registry.k8s.io/sig-storage/csi-snapshotter:v7.0.1
registry.k8s.io/sig-storage/csi-snapshotter:v7.0.2
registry.k8s.io/sig-storage/livenessprobe:v2.10.0
registry.k8s.io/sig-storage/livenessprobe:v2.12.0

**Comment by addyess** [comment]
@jblesener i just saw this issue:
https://github.com/kubernetes/cloud-provider-vsphere/issues/1251

It may be some of these images from prior releases cannot be found.  I'll try to mirror what i can to rocks.cc

**Comment by jblesener** [comment]
@addyess It looks like VMware is republishing some images from the last few releases. I'm not sure if they have plans to fully backfill the missing images. 
https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/3054#issuecomment-2369606679
https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/3053#issuecomment-2364316096

**Pull request closed without merging**
